services:
  sms-gateway:
    build: ./api
    container_name: sms-gateway
    restart: unless-stopped
    ports:
      - "3250:3250"
      - "3251:3251"
    environment:
      - ADMIN_PASSWORD=CHANGEZ_MOI
      - PORT_API=3250
      - PORT_WEB=3251
      - DATA_DIR=/data
    volumes:
      - sms-gateway-data:/data

volumes:
  sms-gateway-data:
